-- PRJ1 Projects access table
create table if not exists public.project_access (
  id bigint generated by default as identity primary key,
  password_hash text not null,
  project_url text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_project_access_active
  on public.project_access (is_active);

-- Keep updated_at current on row updates
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_project_access_updated_at on public.project_access;
create trigger trg_project_access_updated_at
before update on public.project_access
for each row
execute function public.set_updated_at();
